apiVersion: apps/v1
kind: Deployment
metadata:
  name: jinja-deployment
  labels:
    app: jinja_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jinja_app
  template:
    metadata:
      labels:
        app: jinja_app
    spec:
      containers:
      - name: jinja
        image: pyronaid/jinja_dashboard_app:#VERSIONAPP#
        ports:
        - containerPort: 5001
        env:
          - name: BE_URL
            valueFrom:
              configMapKeyRef:
                name: springboot-config
                key: BE_URL
          - name: BE_PORT
            valueFrom:
              configMapKeyRef:
                name: springboot-config
                key: BE_PORT
          - name: BE_LOGIN_API_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: springboot-config
                key: BE_LOGIN_API_ADDRESS
          - name: BE_SIGNUP_API_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: springboot-config
                key: BE_SIGNUP_API_ADDRESS
---
apiVersion: v1
kind: Service
metadata:
  name: jinja-service-ext
spec:
  type: LoadBalancer
  selector:
    app: jinja_app
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30051